version: "3.9"
   
services:
  db:
    restart: always
    container_name: psql
    image: postgres:latest
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}

  redis:
    restart: always
    container_name: redis
    image: redis:latest

  web:
    container_name: blogapp
    restart: always
    build: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/linkgraph
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis