# Generated by Django 3.1.6 on 2021-02-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('NOT_APPROVED', 'Not Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_APPROVED', max_length=12),
        ),
    ]
