# Generated by Django 3.1.6 on 2021-02-06 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210206_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ManyToManyField(blank=True, related_name='reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='edited_by',
            field=models.ManyToManyField(blank=True, related_name='edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
    ]
