# Generated by Django 3.1.6 on 2021-02-06 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210206_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written', to=settings.AUTH_USER_MODEL),
        ),
    ]
