# Generated by Django 3.1.6 on 2021-02-06 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210206_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
